# Generated by Django 4.1.3 on 2022-11-19 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OMMAPP', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentalinformation',
            name='al',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='mentalinformation',
            name='co',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='mentalinformation',
            name='cu',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='mentalinformation',
            name='fe',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='mentalinformation',
            name='mn',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='mentalinformation',
            name='ni',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='mentalinformation',
            name='pb',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='mentalinformation',
            name='si',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='mentalinformation',
            name='zn',
            field=models.FloatField(),
        ),
    ]
