# Generated by Django 4.1.3 on 2022-11-19 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OMMAPP', '0002_alter_mentalinformation_al_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentalinformation',
            name='water_depth',
            field=models.FloatField(),
        ),
    ]
