# Generated by Django 4.1.3 on 2022-11-19 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OMMAPP', '0004_alter_mentalinformation_al_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentalinformation',
            name='water_depth',
            field=models.FloatField(null=True),
        ),
    ]
