# Generated by Django 4.1.3 on 2022-11-20 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OMMAPP', '0005_alter_mentalinformation_water_depth'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentalinformation',
            name='longlatitude',
            field=models.CharField(default=1, max_length=15, verbose_name='经纬度'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mentalinformation',
            name='al',
            field=models.FloatField(null=True, verbose_name='铝'),
        ),
        migrations.AlterField(
            model_name='mentalinformation',
            name='co',
            field=models.FloatField(null=True, verbose_name='钴'),
        ),
        migrations.AlterField(
            model_name='mentalinformation',
            name='cu',
            field=models.FloatField(null=True, verbose_name='铜'),
        ),
        migrations.AlterField(
            model_name='mentalinformation',
            name='fe',
            field=models.FloatField(null=True, verbose_name='铁'),
        ),
        migrations.AlterField(
            model_name='mentalinformation',
            name='mn',
            field=models.FloatField(null=True, verbose_name='锰'),
        ),
        migrations.AlterField(
            model_name='mentalinformation',
            name='ni',
            field=models.FloatField(null=True, verbose_name='镍'),
        ),
        migrations.AlterField(
            model_name='mentalinformation',
            name='pb',
            field=models.FloatField(null=True, verbose_name='铅'),
        ),
        migrations.AlterField(
            model_name='mentalinformation',
            name='si',
            field=models.FloatField(null=True, verbose_name='硅'),
        ),
        migrations.AlterField(
            model_name='mentalinformation',
            name='water_depth',
            field=models.FloatField(null=True, verbose_name='水深'),
        ),
        migrations.AlterField(
            model_name='mentalinformation',
            name='zn',
            field=models.FloatField(null=True, verbose_name='锌'),
        ),
    ]
