# Generated by Django 4.1.3 on 2022-11-20 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OMMAPP', '0006_mentalinformation_longlatitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentalinformation',
            name='longlatitude',
            field=models.CharField(max_length=30, verbose_name='经纬度'),
        ),
    ]
